language: perl

os:
  - linux
  # - osx

# services:
  # - docker

perl:
  # - "5.26-extras"
  - "5.24-extras"
  - "5.22-extras"
  - "5.20-extras"
  - "5.18-extras"

install:
  - cpanm --skip-satisfied -n -q Config::Auto warnings::unused IO::Socket::INET Net::Server::Mail::SMTP Net::SMTP Net::DNS Geo::IP Net::Whois::IP Net::Whois::IANA Locale::Country Data::Validate::IP CHI Mail::Address Sys::Syslog

script:
  - perl -MO=Lint ./smtp-server
  - perl -c -Mwarnings::unused ./smtp-server
