language: perl

os:
  - linux
  # - osx

arch:
 - amd64
 # - arm64	# Gets 404 error

# services:
  # - docker

sudo: false

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  # - "5.20"
  # - "5.18"
  # - "5.16"
  # - "5.14"
  # - "5.12"

install:
  - cpanm -iqn Config::Auto warnings::unused IO::Socket::INET Net::Server::Mail::SMTP Net::SMTP Net::DNS Geo::IP Net::Whois::IP Net::Whois::IANA Locale::Country Data::Validate::IP CHI Mail::Address Sys::Syslog B::Lint Mail::DKIM::Verifier ClamAV::Client

script:
  - perl -MO=Lint ./smtp-proxy
  - perl -c -Mwarnings::unused ./smtp-proxy

jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - cinst -y strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
      install:
        - cpanm -iqn Config::Auto warnings::unused IO::Socket::INET Net::Server::Mail::SMTP Net::SMTP Net::DNS Geo::IP Net::Whois::IP Net::Whois::IANA Locale::Country Data::Validate::IP CHI Mail::Address Sys::Syslog B::Lint Mail::DKIM::Verifier ClamAV::Client
      script:
        - perl -MO=Lint ./smtp-proxy
        - perl -c -Mwarnings::unused ./smtp-proxy
